"""Policy improvement from trajectories generated by deployed hybrid inference."""

from __future__ import annotations

import argparse
import copy
import json
import subprocess
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

import catan_py

try:
    from .catanzero import (
        CATANZERO_VERSION,
        SUPPORTED_CATANZERO_VERSIONS,
        CatanZeroNet,
        load_catanzero,
    )
except ImportError:
    from catanzero import (
        CATANZERO_VERSION,
        SUPPORTED_CATANZERO_VERSIONS,
        CatanZeroNet,
        load_catanzero,
    )


ROOT = Path(__file__).resolve().parents[1]
PYTHON = ROOT / ".venv/bin/python"
EXPORTER = ROOT / "training/export_net.py"
EVALUATOR = ROOT / "training/evaluate_planner_vs_alpha.py"


def load_policy_model(path: Path):
    payload = torch.load(path, map_location="cpu", weights_only=False)
    if payload.get("catanzero_version") in SUPPORTED_CATANZERO_VERSIONS:
        return load_catanzero(path)
    model = CatanZeroNet(payload["config"]["hidden"])
    state = payload["model_state"]
    model.trunk.load_state_dict(
        {
            key.removeprefix("trunk."): value
            for key, value in state.items()
            if key.startswith("trunk.")
        }
    )
    model.policy.load_state_dict(
        {
            key.removeprefix("policy."): value
            for key, value in state.items()
            if key.startswith("policy.")
        }
    )
    with torch.no_grad():
        model.policy_type.weight.zero_()
        model.policy_type.bias.zero_()
        model.outcome.weight.zero_()
        model.outcome.bias.zero_()
        model.outcome.weight[0].copy_(state["value.weight"][0])
        model.outcome.bias[0].copy_(state["value.bias"][0])
    return model.eval()


def hybrid_policy(
    net_path: Path,
    seed: int,
    opponent: str,
    *,
    late_net_path: Path | None = None,
    late_net_min_vp: int = 5,
    final_net_path: Path | None = None,
    final_net_min_vp: int = 6,
    final_net_min_cities: int = 0,
    final_net_max_cities: int = 4,
    final_net_seat_mask: int = 15,
    opening_wheat_weight: float = 0.0,
    immediate_vp_min: int = 0,
    search_vp_gain_weight: float = 0.0,
    search_building_gain_weight: float = 0.0,
    search_road_control_weight: float = 0.0,
    search_max_vp: int = 7,
    search_max_hidden_vp: int = 5,
    end_turn_trade_sweep_max_vp: int = 7,
    independent_rollout_seeds: bool = False,
):
    alpha_opponent = opponent == "alpha"
    return catan_py.OpeningHybridPolicy(
        str(net_path),
        late_net_path=str(late_net_path) if late_net_path is not None else None,
        late_net_min_vp=late_net_min_vp,
        final_net_path=str(final_net_path) if final_net_path is not None else None,
        final_net_min_vp=final_net_min_vp,
        final_net_min_cities=final_net_min_cities,
        final_net_max_cities=final_net_max_cities,
        final_net_seat_mask=final_net_seat_mask,
        search_vp_gain_weight=search_vp_gain_weight,
        search_building_gain_weight=search_building_gain_weight,
        search_road_control_weight=search_road_control_weight,
        search_max_vp=search_max_vp,
        search_max_hidden_vp=search_max_hidden_vp,
        end_turn_trade_sweep_max_vp=end_turn_trade_sweep_max_vp,
        heuristic="v2",
        seed=seed,
        strategy_settlement_weight=5.0,
        opening_production_weight=1.0,
        opening_wheat_weight=opening_wheat_weight,
        opening_settlement_lookahead=True,
        opening_rollout_candidates=12,
        opening_rollout_samples=32,
        opening_rollout_finalists=3,
        opening_rollout_final_samples=128,
        opening_rollout_prior_weight=0.04 if alpha_opponent else 0.055,
        common_rollout_random_numbers=alpha_opponent,
        independent_rollout_seeds=independent_rollout_seeds,
        heuristic_refinement=True,
        endgame_conversion=True,
        immediate_vp_min=immediate_vp_min,
        road_refinement=True,
        knight_pressure=alpha_opponent,
        leader_robber_weight=1.0,
        resource_tactics=True,
    )


def collect_lineup(
    net_path: Path,
    *,
    opponent: str,
    candidate_seat: int,
    games: int,
    seed: int,
    alpha_net: str,
    alpha_root_k: int,
    alpha_samples: int,
    alpha_depth: int,
):
    seats = [opponent] * 4
    seats[candidate_seat] = "policy"
    env = catan_py.VecEnv(
        games,
        victory_target=7,
        visibility="realistic",
        zero_sum=True,
        seed=seed,
        seats=seats,
        alpha_net=alpha_net if opponent == "alpha" else None,
        alpha_root_k=alpha_root_k,
        alpha_samples=alpha_samples,
        alpha_depth=alpha_depth,
    )
    policy = hybrid_policy(net_path, seed, opponent)
    obs, masks, _ = env.observe()
    obs = np.asarray(obs)
    masks = np.asarray(masks)
    active = [[] for _ in range(games)]
    finished = np.zeros(games, dtype=bool)
    trajectories = []

    while not bool(finished.all()):
        actions = np.asarray(policy.actions(env), dtype=np.uint32)
        live = np.flatnonzero(~finished)
        for index in live:
            active[index].append(
                {
                    "obs": obs[index].copy(),
                    "mask": masks[index].copy(),
                    "action": int(actions[index]),
                }
            )
        obs, masks, _, _, dones, terminals = env.step(actions)
        obs = np.asarray(obs)
        masks = np.asarray(masks)
        dones = np.asarray(dones)
        terminals = np.asarray(terminals)
        for index in np.flatnonzero(dones & ~finished):
            win = bool(terminals[index, candidate_seat] > 0)
            trajectories.append(
                {
                    "opponent": opponent,
                    "candidate_seat": candidate_seat,
                    "win": win,
                    "outcome": float(terminals[index, candidate_seat]),
                    "samples": active[index],
                }
            )
            finished[index] = True
    return trajectories


def collect_trajectories(
    net_path: Path,
    *,
    heuristic_v1_games: int,
    heuristic_v2_games: int,
    alpha_games: int,
    seed: int,
    alpha_net: str,
    alpha_root_k: int,
    alpha_samples: int,
    alpha_depth: int,
):
    trajectories = []
    schedule = (
        ("heuristic", heuristic_v1_games),
        ("heuristic_v2", heuristic_v2_games),
        ("alpha", alpha_games),
    )
    for opponent_index, (opponent, games) in enumerate(schedule):
        if games <= 0:
            continue
        if games % 4:
            raise ValueError("games per opponent must be divisible by four")
        games_per_seat = games // 4
        for seat in range(4):
            trajectories.extend(
                collect_lineup(
                    net_path,
                    opponent=opponent,
                    candidate_seat=seat,
                    games=games_per_seat,
                    seed=seed + opponent_index * 1_000_003 + seat * 100_003,
                    alpha_net=alpha_net,
                    alpha_root_k=alpha_root_k,
                    alpha_samples=alpha_samples,
                    alpha_depth=alpha_depth,
                )
            )
    return trajectories


def configure_policy_parameters(model):
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    parameters = [
        *model.policy.parameters(),
        *model.policy_type.parameters(),
    ]
    for parameter in parameters:
        parameter.requires_grad_(True)
    return parameters


def fit_hybrid_elites(
    model,
    reference,
    trajectories,
    *,
    learning_rate: float,
    epochs: int,
    minibatch_size: int,
    loss_weight: float,
    kl_scale: float,
    recency_weight: float,
):
    samples = []
    for trajectory in trajectories:
        outcome_weight = 1.0 if trajectory["win"] else loss_weight
        denominator = max(1, len(trajectory["samples"]) - 1)
        for index, sample in enumerate(trajectory["samples"]):
            progress = index / denominator
            weight = outcome_weight * (1.0 + recency_weight * progress)
            samples.append({**sample, "weight": weight})
    parameters = configure_policy_parameters(model)
    optimizer = torch.optim.Adam(parameters, lr=learning_rate)
    totals = {"loss": 0.0, "imitation_loss": 0.0, "kl_loss": 0.0}
    updates = 0

    for _ in range(epochs):
        order = torch.randperm(len(samples))
        for indexes in order.split(minibatch_size):
            batch = [samples[int(index)] for index in indexes]
            obs = torch.as_tensor(np.stack([sample["obs"] for sample in batch]))
            mask = torch.as_tensor(np.stack([sample["mask"] for sample in batch]))
            actions = torch.as_tensor(
                [sample["action"] for sample in batch],
                dtype=torch.int64,
            )
            weights = torch.as_tensor(
                [sample["weight"] for sample in batch],
                dtype=torch.float32,
            )
            logits = model(obs)["logits"].masked_fill(~mask, -1e9)
            log_policy = torch.log_softmax(logits, dim=1)
            imitation_loss = -(
                log_policy.gather(1, actions.unsqueeze(1)).squeeze(1) * weights
            ).sum() / weights.abs().sum().clamp_min(1.0)
            with torch.no_grad():
                reference_logits = reference(obs)["logits"].masked_fill(~mask, -1e9)
                reference_policy = torch.softmax(reference_logits, dim=1)
            kl_loss = (
                reference_policy
                * (
                    torch.log(reference_policy.clamp_min(1e-12))
                    - log_policy
                )
            ).masked_fill(~mask, 0.0).sum(dim=1).mean()
            loss = imitation_loss + kl_scale * kl_loss
            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(parameters, 0.5)
            optimizer.step()
            totals["loss"] += float(loss.item())
            totals["imitation_loss"] += float(imitation_loss.item())
            totals["kl_loss"] += float(kl_loss.item())
            updates += 1
    return {
        "games": len(trajectories),
        "wins": sum(trajectory["win"] for trajectory in trajectories),
        "samples": len(samples),
        **{key: value / updates for key, value in totals.items()},
    }


def fit_hybrid_outcome(
    model,
    trajectories,
    *,
    learning_rate: float,
    epochs: int,
    minibatch_size: int,
    recency_weight: float,
):
    samples = []
    for trajectory in trajectories:
        count = max(len(trajectory["samples"]), 1)
        for index, sample in enumerate(trajectory["samples"]):
            progress = (index + 1) / count
            samples.append(
                {
                    "obs": sample["obs"],
                    "outcome": trajectory["outcome"],
                    "weight": 1.0 + recency_weight * progress,
                }
            )
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    for parameter in model.outcome.parameters():
        parameter.requires_grad_(True)
    optimizer = torch.optim.Adam(model.outcome.parameters(), lr=learning_rate)
    totals = {"outcome_loss": 0.0}
    updates = 0

    for _ in range(epochs):
        order = torch.randperm(len(samples))
        for indexes in order.split(minibatch_size):
            batch = [samples[int(index)] for index in indexes]
            obs = torch.as_tensor(np.stack([sample["obs"] for sample in batch]))
            targets = torch.as_tensor(
                [sample["outcome"] for sample in batch],
                dtype=torch.float32,
            )
            weights = torch.as_tensor(
                [sample["weight"] for sample in batch],
                dtype=torch.float32,
            )
            predictions = model(obs)["outcome"][:, 0]
            loss = ((predictions - targets).pow(2) * weights).sum() / weights.sum()
            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.outcome.parameters(), 0.5)
            optimizer.step()
            totals["outcome_loss"] += float(loss.item())
            updates += 1
    return {
        "games": len(trajectories),
        "wins": sum(trajectory["win"] for trajectory in trajectories),
        "samples": len(samples),
        **{key: value / updates for key, value in totals.items()},
    }


def save_candidate(path: Path, source_payload, model, iteration: int, config: dict):
    payload = dict(source_payload)
    payload["catanzero_version"] = CATANZERO_VERSION
    payload["model_state"] = model.state_dict()
    payload["optimizer_state"] = {}
    payload["hybrid_improvement_iteration"] = iteration
    payload["hybrid_improvement_config"] = config
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(payload, path)


def export_candidate(checkpoint: Path, net_path: Path):
    subprocess.run(
        [str(PYTHON), str(EXPORTER), str(checkpoint), str(net_path)],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )


def evaluate_hybrid(
    net_path: Path,
    opponent: str,
    games: int,
    seed: int,
    *,
    independent_rollout_seeds: bool = False,
):
    command = [
        str(PYTHON),
        str(EVALUATOR),
        str(net_path),
        "--opponent",
        opponent,
        "--planner",
        "hybrid-v2",
        "--strategy-settlement-weight",
        "5",
        "--opening-production-weight",
        "1",
        "--opening-settlement-lookahead",
        "--opening-rollout-candidates",
        "12",
        "--opening-rollout-samples",
        "32",
        "--opening-rollout-finalists",
        "3",
        "--opening-rollout-final-samples",
        "128",
        "--opening-rollout-prior-weight",
        "0.055",
        "--heuristic-refinement",
        "--endgame-conversion",
        "--road-refinement",
        "--immediate-vp-min",
        "0",
        "--leader-robber-weight",
        "1",
        "--resource-tactics",
        "--games",
        str(games),
        "--seed",
        str(seed),
    ]
    if opponent == "alpha":
        command.extend(
            [
                "--opening-rollout-prior-weight",
                "0.04",
                "--common-rollout-random-numbers",
                "--knight-pressure",
            ]
        )
    if independent_rollout_seeds:
        command.append("--independent-rollout-seeds")
    result = subprocess.run(
        command,
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("checkpoint", type=Path)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--iterations", type=int, default=4)
    parser.add_argument(
        "--heuristic-games",
        type=int,
        default=None,
        help="Set both heuristic-v1 and heuristic-v2 collection counts.",
    )
    parser.add_argument("--heuristic-v1-games", type=int, default=128)
    parser.add_argument("--heuristic-v2-games", type=int, default=128)
    parser.add_argument("--alpha-games", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--minibatch-size", type=int, default=1024)
    parser.add_argument("--loss-weight", type=float, default=0.1)
    parser.add_argument("--kl-scale", type=float, default=1.0)
    parser.add_argument("--policy-recency-weight", type=float, default=0.0)
    parser.add_argument("--outcome-head-only", action="store_true")
    parser.add_argument("--outcome-recency-weight", type=float, default=4.0)
    parser.add_argument("--eval-games", type=int, default=32)
    parser.add_argument("--seed", type=int, default=29_000_000)
    parser.add_argument("--alpha-net", default="models/catan-512.ctnn")
    parser.add_argument("--alpha-root-k", type=int, default=8)
    parser.add_argument("--alpha-samples", type=int, default=96)
    parser.add_argument("--alpha-depth", type=int, default=300)
    args = parser.parse_args()
    if args.heuristic_games is not None:
        args.heuristic_v1_games = args.heuristic_games
        args.heuristic_v2_games = args.heuristic_games

    torch.manual_seed(args.seed)
    torch.set_num_threads(10)
    args.run_dir.mkdir(parents=True, exist_ok=True)
    source_payload = torch.load(
        args.checkpoint,
        map_location="cpu",
        weights_only=False,
    )
    model = load_policy_model(args.checkpoint)
    reference = copy.deepcopy(model).eval()
    current_checkpoint = args.checkpoint
    current_net = args.run_dir / "iteration_00.ctnn"
    export_candidate(current_checkpoint, current_net)
    config = {
        key: str(value) if isinstance(value, Path) else value
        for key, value in vars(args).items()
    }
    history = []

    for iteration in range(1, args.iterations + 1):
        started = time.time()
        trajectories = collect_trajectories(
            current_net,
            heuristic_v1_games=args.heuristic_v1_games,
            heuristic_v2_games=args.heuristic_v2_games,
            alpha_games=args.alpha_games,
            seed=args.seed + iteration * 10_000_019,
            alpha_net=args.alpha_net,
            alpha_root_k=args.alpha_root_k,
            alpha_samples=args.alpha_samples,
            alpha_depth=args.alpha_depth,
        )
        if args.outcome_head_only:
            fit = fit_hybrid_outcome(
                model,
                trajectories,
                learning_rate=args.lr,
                epochs=args.epochs,
                minibatch_size=args.minibatch_size,
                recency_weight=args.outcome_recency_weight,
            )
        else:
            fit = fit_hybrid_elites(
                model,
                reference,
                trajectories,
                learning_rate=args.lr,
                epochs=args.epochs,
                minibatch_size=args.minibatch_size,
                loss_weight=args.loss_weight,
                kl_scale=args.kl_scale,
                recency_weight=args.policy_recency_weight,
            )
        current_checkpoint = args.run_dir / f"iteration_{iteration:02d}.pt"
        current_net = args.run_dir / f"iteration_{iteration:02d}.ctnn"
        save_candidate(current_checkpoint, source_payload, model, iteration, config)
        export_candidate(current_checkpoint, current_net)
        evaluation = {
            opponent: evaluate_hybrid(
                current_net,
                opponent,
                args.eval_games,
                args.seed + iteration * 1_000_003,
            )
            for opponent in ("heuristic", "heuristic_v2")
        }
        event = {
            "iteration": iteration,
            "fit": fit,
            "collection": {
                opponent: {
                    "games": sum(
                        trajectory["opponent"] == opponent
                        for trajectory in trajectories
                    ),
                    "wins": sum(
                        trajectory["opponent"] == opponent and trajectory["win"]
                        for trajectory in trajectories
                    ),
                }
                for opponent in ("heuristic", "heuristic_v2", "alpha")
            },
            "evaluation": evaluation,
            "seconds": time.time() - started,
            "checkpoint": str(current_checkpoint),
            "net": str(current_net),
        }
        history.append(event)
        (args.run_dir / "history.json").write_text(json.dumps(history, indent=2))
        print(json.dumps(event, sort_keys=True), flush=True)


if __name__ == "__main__":
    main()
